[package]
name = "sfnutils-rs"
version = "0.1.0"
authors = ["psvenk <45520974+psvenk@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
